name: "\U0001F6A8 Technical issue"
description: When you're experiencing problems using the container
body:
  - type: input
    id: os
    attributes:
      label: Operating system
      description: Your Linux distribution (can be shown by `lsb_release -a`).
      placeholder: e.g. Ubuntu 24.04
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: A clear and concise description of your issue.
    validations:
      required: true
  - type: textarea
    id: compose
    attributes:
      label: Docker compose
      description: The compose file (or otherwise the `docker run` command used).
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Docker log
      description: The logfile of the container (as shown by `docker logs dsm`).
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots (optional)
      description: Screenshots that might help to make the problem more clear.
    validations:
      required: false
