name: "\U00002753 General question"
description: Questions about the container not related to an issue
title: "[Question]: "
labels: ["question"]
body:
  - type: checkboxes
    attributes:
      label: Is your question not already answered in the FAQ?
      description: Please read the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md) carefully to avoid asking duplicate questions.
      options:
      - label: I made sure the question is not listed in the [FAQ](https://github.com/vdsm/virtual-dsm/blob/master/readme.md).
        required: true
  - type: checkboxes
    attributes:
      label: Is this a general question and not a technical issue?
      description: For questions related to issues you must use the [technical issue](https://github.com/vdsm/virtual-dsm/issues/new?assignees=&labels=&projects=&template=1-issue.yml) form instead. It contains all the right fields (system info, logfiles, etc.) we need in order to be able to help you.
      options:
      - label: I am sure my question is not about a technical issue.
        required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What's the question you have about the container?
    validations:
      required: true
